### ISSUE TITLE
Panel Info Page

### ISSUE THREAD

**Issue by rgbayrak** [ohbm/osr2022#14]
Update panel page with speaker info.

**Comment by rgbayrak** [comment]
We have a speakers.csv with the speaker info under _data folder, photos of speakers under img/speakers folder.


**We need** to have these speakers show up under their respective panels listed with their roles (i.e. Co-moderator, Speaker). The formatting can be adapted from https://ohbm.github.io/osr2020/speakers/ with the aforementioned design choice. Design should include the feature, once clicked on the speaker photo, a mini info page about the speaker opens in a new tab.

**Comment by rgbayrak** [comment]
If the speakers don't have photos, maybe add an avatar with their initials?

**Comment by NeuroShepherd** [comment]
Currently working through this

Progress: 
- have figured out how to loop through the fields in ./_data/speakers.csv
- writing conditional statements to filter the CSV by Panel
- discovered that Jekyll doesn't like umlauts (¨) due to some UTF-8 encoding issue with CSV files so I'll be removing special characters e.g. Düsseldorf -> Duesseldorf
- have added a column to the speakers.csv that is a relative path to photos stored ./img

TODO:
- make things pretty. I'll probably start by directly mimicking the linked OHBM 2020 page
- an avatar/initials for speakers without photos would be great!

**Comment by rgbayrak** [comment]
Excellent! @NeuroShepherd be aware that @NaomiGaggi has been updating this csv file as we hear from other speakers. You two maybe can be in contact so no overrides on the file you are working on.

**Comment by NaomiGaggi** [comment]
I just updated the speakers.csv file with all of the up to date speakers and info. I won't touch the file until I have you're OK. Which .csv file were you working with? @NeuroShepherd

**Comment by rgbayrak** [comment]
@NeuroShepherd any updates?

**Comment by vborghe** [comment]
I can't close it, but the always amazing @RaphaelMeudec solved it 🙏

**Comment by rgbayrak** [comment]
Good job @RaphaelMeudec! Looks great.

**Comment by NaomiGaggi** [comment]
@RaphaelMeudec 👏👏👏👏👏
